/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import model from '../../assets/3d/new.glb'
export function Model3(props) {
  const { nodes, materials } = useGLTF(model)
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve001.geometry}
        material={nodes.Curve001.material}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve002.geometry}
        material={nodes.Curve002.material}
        position={[-0.287, -0.273, -0.008]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve003.geometry}
        material={nodes.Curve003.material}
        position={[-0.287, -0.273, -0.008]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve004.geometry}
        material={nodes.Curve004.material}
        position={[-0.287, -0.273, -0.008]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve005.geometry}
        material={nodes.Curve005.material}
        position={[-0.287, -0.273, -0.008]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve006.geometry}
        material={nodes.Curve006.material}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve007.geometry}
        material={nodes.Curve007.material}
        position={[-0.287, -0.273, -0.005]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve008.geometry}
        material={nodes.Curve008.material}
        position={[-0.287, -0.273, -0.005]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve009.geometry}
        material={nodes.Curve009.material}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve010.geometry}
        material={nodes.Curve010.material}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve011.geometry}
        material={nodes.Curve011.material}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve012.geometry}
        material={nodes.Curve012.material}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve014.geometry}
        material={nodes.Curve014.material}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve015.geometry}
        material={nodes.Curve015.material}
        position={[-0.287, -0.273, -0.011]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve016.geometry}
        material={nodes.Curve016.material}
        position={[-0.287, -0.273, -0.011]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve017.geometry}
        material={nodes.Curve017.material}
        position={[-0.287, -0.273, -0.011]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve018.geometry}
        material={nodes.Curve018.material}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve019.geometry}
        material={nodes.Curve019.material}
        position={[-0.287, -0.273, -0.027]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve020.geometry}
        material={nodes.Curve020.material}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve021.geometry}
        material={nodes.Curve021.material}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve022.geometry}
        material={nodes.Curve022.material}
        position={[-0.287, -0.273, -0.009]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve023.geometry}
        material={nodes.Curve023.material}
        position={[-0.287, -0.273, -0.009]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve024.geometry}
        material={nodes.Curve024.material}
        position={[-0.287, -0.273, -0.009]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve025.geometry}
        material={nodes.Curve025.material}
        position={[-0.287, -0.273, -0.009]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve026.geometry}
        material={nodes.Curve026.material}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve027.geometry}
        material={nodes.Curve027.material}
        position={[-0.287, -0.273, -0.009]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve028.geometry}
        material={nodes.Curve028.material}
        position={[-0.287, -0.273, -0.009]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve030.geometry}
        material={materials.SVGMat}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve031.geometry}
        material={materials.SVGMat}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve032.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve033.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve034.geometry}
        material={materials.SVGMat}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve035.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve036.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve037.geometry}
        material={materials.SVGMat}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve038.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve039.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve040.geometry}
        material={materials.SVGMat}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve041.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve042.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve043.geometry}
        material={materials.SVGMat}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve044.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve045.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve046.geometry}
        material={materials.SVGMat}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve047.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve048.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve049.geometry}
        material={materials.SVGMat}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve050.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve051.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve052.geometry}
        material={materials.SVGMat}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve053.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve054.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve055.geometry}
        material={materials.SVGMat}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve056.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve057.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve058.geometry}
        material={materials.SVGMat}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve059.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve060.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve061.geometry}
        material={materials.SVGMat}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve062.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve063.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve064.geometry}
        material={materials.SVGMat}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve065.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve066.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve067.geometry}
        material={materials.SVGMat}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve068.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve069.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve070.geometry}
        material={materials.SVGMat}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve071.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve072.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve073.geometry}
        material={materials.SVGMat}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve074.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve075.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve076.geometry}
        material={materials.SVGMat}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve077.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve078.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve079.geometry}
        material={materials.SVGMat}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve080.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve081.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve082.geometry}
        material={materials.SVGMat}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve083.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve084.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve085.geometry}
        material={materials.SVGMat}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve086.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve087.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve088.geometry}
        material={materials.SVGMat}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve089.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve090.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve091.geometry}
        material={materials.SVGMat}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve092.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve093.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve094.geometry}
        material={materials.SVGMat}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve095.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve096.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve097.geometry}
        material={materials.SVGMat}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve098.geometry}
        material={nodes.Curve098.material}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve100.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.015]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve101.geometry}
        material={nodes.Curve101.material}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve103.geometry}
        material={nodes.Curve103.material}
        position={[-0.287, -0.273, -0.062]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve104.geometry}
        material={nodes.Curve104.material}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve106.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.016]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve107.geometry}
        material={nodes.Curve107.material}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve110.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.025]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve113.geometry}
        material={nodes.Curve113.material}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve116.geometry}
        material={materials['SVGMat.001']}
        position={[-0.287, -0.273, -0.012]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve117.geometry}
        material={nodes.Curve117.material}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve120.geometry}
        material={nodes.Curve120.material}
        position={[-0.287, -0.273, 0.009]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve121.geometry}
        material={materials.SVGMat}
        position={[-0.287, -0.273, -0.149]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={64.233}
      />
    </group>
  )
}

useGLTF.preload(model);
export default Model3;

