/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import model from '../../assets/3d/3-Shapes.glb'

export function Model(props) {
  const { nodes, materials } = useGLTF(model)
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve446.geometry}
        material={materials['SVGMat.017']}
        position={[-1.87, 0.89, -2.753]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={12.983}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve447.geometry}
        material={nodes.Curve447.material}
        position={[-1.871, 0.504, -2.753]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={12.983}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve448.geometry}
        material={materials['SVGMat.018']}
        position={[-1.873, 1.035, -2.753]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={12.983}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve449.geometry}
        material={materials['SVGMat.019']}
        position={[-1.842, 0.787, -2.753]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={12.983}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve581.geometry}
        material={nodes.Curve581.material}
        position={[-0.329, 1.216, -3.524]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={17.427}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve707.geometry}
        material={materials['SVGMat.010']}
        position={[0.018, 1.125, -3.559]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={15.513}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve708.geometry}
        material={nodes.Curve708.material}
        position={[0.017, 0.665, -3.559]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={15.513}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve709.geometry}
        material={materials['SVGMat.011']}
        position={[0.017, 1.253, -3.559]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={15.513}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve710.geometry}
        material={materials['SVGMat.010']}
        position={[0.017, 1.364, -3.559]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={15.513}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve711.geometry}
        material={materials['SVGMat.010']}
        position={[0.025, 1.246, -3.559]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={15.513}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve712.geometry}
        material={materials['SVGMat.012']}
        position={[0.014, 1.244, -3.559]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={15.513}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve716.geometry}
        material={nodes.Curve716.material}
        position={[0.017, 1.366, -3.559]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={15.513}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve717.geometry}
        material={materials['SVGMat.013']}
        position={[-0.01, 0.999, -3.559]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={15.513}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve718.geometry}
        material={materials['SVGMat.014']}
        position={[0.78, 1.025, -0.159]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={13.547}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve719.geometry}
        material={nodes.Curve719.material}
        position={[0.779, 0.622, -0.159]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={13.547}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve720.geometry}
        material={nodes.Curve720.material}
        position={[0.781, 1.145, -0.159]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={13.547}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve721.geometry}
        material={nodes.Curve721.material}
        position={[0.781, 1.217, -0.159]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={13.547}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve722.geometry}
        material={materials['SVGMat.015']}
        position={[0.781, 1.126, -0.159]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={13.547}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve723.geometry}
        material={materials['SVGMat.016']}
        position={[0.804, 0.917, -0.159]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={13.547}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={materials['GREEN CIRCLE']}
        position={[-2.203, 0.713, -2.715]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.125}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text001.geometry}
        material={materials['GREEN CIRCLE']}
        position={[-0.259, 0.866, -3.512]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.125}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text002.geometry}
        material={materials.Material}
        position={[-0.077, 1.218, -3.489]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.072}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text003.geometry}
        material={materials['GREEN CIRCLE']}
        position={[0.458, 0.866, -0.118]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.125}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve003.geometry}
        material={materials['SVGMat.012']}
        position={[0.017, 1.241, -3.546]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[10.591, 14.125, 7.632]}
      />
    </group>
  )
}

useGLTF.preload(model)
export default Model;
